languageCode = "en"
languageName = "English"
weight = 1

title = "Yueshan Zhang" 

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  description = "Academic portfolio of Yueshan Zhang - Mathematics undergraduate at Nankai University & Research Assistant at UC Berkeley." 
  
  # logo = "img/logo.png" 
  
  # copyright = "© 2025 Yueshan Zhang"
  
  dateFormat = "2 January 2006"

[params.author]
  name = "Yueshan Zhang"  
  # 4. 头像：关键！你需要把一张照片重命名为 avatar.jpg 放到 assets/img/ 文件夹里
  image = "img/avatar.jpg" 
  headline = "B.S. in Math @ Nankai Univ. | Incoming PhD Applicant"
  
  # 或者强调你的研究身份：
  # headline = "Research Assistant @ UC Berkeley | Math @ Nankai"

  # 6. 个人简介 (Bio)：这是下面的一行小字
  # 结合你的研究兴趣（大模型/数字孪生、因果推断）：
  bio = "Researching Causal Inference & LLMs (Digital Twins). Interested in Statistics and Biostatistics."
  # links = [
  #   { email = "mailto:hello@your_domain.com" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
  #   { github = "https://github.com/username" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { linkedin = "https://linkedin.com/in/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { twitter = "https://twitter.com/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
  #   { ko-fi = "https://ko-fi.com/username" },
  # ]
